# sys库的用例
import sys
# 获取命令行参数列表
print("命令行参数列表:", sys.argv)
# 获取标准输入流，输出流和错误流对象
print("标准输入流:", sys.stdin)
print("标准输出流:", sys.stdout)
print("标准错误流:", sys.stderr)
# 获取Python解释器的版本信息
print("版本信息:", sys.version)
# 获取Python解释器的路径
print("路径:", sys.executable)
# 获取当前平台的名称
print("平台名称:", sys.platform)
# 获取当前系统的最大整数值和浮点数精度
print("最大整数值:", sys.maxsize)
print("浮点数精度:", sys.float_info.epsilon)
# 获取当前系统的模块搜索路径列表
print("模块搜索路径列表:", sys.path)
# 退出程序，可选参数为退出状态码，默认为0（正常退出）
sys.exit (1)
